---
language: node_js
node_js:
  - "stable"

sudo: false
dist: trusty

addons:
  chrome: stable

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
before_install:
  - npm install -g npm@5 # skip this if you are using node 9
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install:
  - yarn install --non-interactive

script:
  - yarn test
