---
language: node_js
node_js:
  - "8"

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - npm install -g greenkeeper-lockfile@1

before_script:
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload

install:
  - yarn install --non-interactive

script:
  - npm run lint:js
  - npm test

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
